### PR TITLE
Updated Ukrainian translation

### PR DESCRIPTION
**Pull request by WallK**
Translated some new strings, changed the Ukrainian for "Bucket" to literal bucket (to align with concept of rain)

### CODE REVIEW

**Comment by WallK** [comment]
Some questions:
What is "Avenue"? There's some description, but this is a new concept in this version, I assume

Also "Change", is it a verb or a noun? (recently added string)

**Comment by WallK** [comment]
Ah, also, proper language code is "uk"
"ua" is a country name
Should I rename the file?

**Comment by iffy** [comment]
> Some questions: What is "Avenue"? There's some description, but this is a new concept in this version, I assume
An avenue is a road, path or channel that a device uses to reach another device. The types of avenues currently supported are: a shared folder, a relay connection or a direct server connection.

> Also "Change", is it a verb or a noun? (recently added string)
It's a noun (I'll add a comment for future translations)

> Ah, also, proper language code is "uk"
> "ua" is a country name
> Should I rename the file?
Thanks for letting me know! No, please leave it and I'll rename it when I bundle the new translations.

**Comment by WallK** [comment]
Thought veeeery hard and decided on a word for "Avenues" that mean something like a small path (because it sounds nice in Ukrainian)
Could be changed after using the app and deciding on another variant, if it's ok

**Comment by iffy** [comment]
Sounds great, Дякую тобі!

**Pull request merged**
