### PR TITLE
Updated French Translation

### PR DESCRIPTION
**Pull request by Limezy**

### CODE REVIEW

**Comment by iffy** [comment]
@Limezy hmm.... this includes a bunch of extra changes (or at least it looks like it does according to GitHub).  I'll manually pull the new file in.  I've got to figure out a better way for you to keep your master branch up to date.

**Comment by Limezy** [comment]
Yes please !
I don’t have the rights to push any modification on /buckets/translations.
Therefore, I need to pull all changes, commit to my own /Limezy/translations branch, then make my changes, commit again, push to my repository, then do a Pull Request !
Not really easy :/

**Comment by iffy** [comment]
@Limezy Does this work?

1. Go to this page: https://github.com/buckets/translations/blob/master/langs/fr.tsx (which is the `fr.tsx` file in this main repo)
2. Click the pencil icon to edit the file screen shot 2018-04-26 at 10 01 15 am

**Comment by Limezy** [comment]
Nope. Well, yes but cannot save. See attached.

**Comment by iffy** [comment]
@Limezy I think the attachment you emailed didn't get automatically added to this issue.

@carlosedubarreto When you supply new translations, do you simply click the pencil icon [on this page](https://github.com/buckets/translations/blob/master/langs/pt.tsx)?

**Comment by carlosedubarreto** [comment]
Yep Matt, I´ve clicked on the pencil on this site you´ve linked

2018-04-30 15:45 GMT-03:00 Matt Haggard <notifications@github.com>:

**Comment by Limezy** [comment]
I've deleted my branch, this is OK.
I cleard everything on my computer to start from scratch.
I went to your link (https://github.com/buckets/translations/blob/master/langs/fr.tsx) then clicked on the desktop icon (capture d ecran 2018-05-01 a 14 40 39) to open it in my Github desktop application.
I made a small test change then tried to push my change to the repo.
As always, I get this error : 
capture d ecran 2018-05-01 a 14 42 04

This is why I made a fork to push on my repository and then make a pull request based on a fork comparison... 

Using the pencil icon, I'm able to do some changes and submit them.
However, I don't think this is a very good solution for the long term, I really would prefer to be on my desktop when I have a big batch of new strings to translate !

**Comment by iffy** [comment]
@Limezy Oh, I didn't know you were using GitHub Desktop.  Now it makes a lot more sense :)

I downloaded GitHub Desktop to see how to make it work well and I think this will work:

1. Change *Current Branch* to master
2. Click *Branch* menu > *Merge Into Current Branch*
3. Choose `upstream/master`
    screen shot 2018-05-01 at 8 05 24 am
4. Click *Merge into master*
5. Make changes to the files
6. Click *Branch* menu > *Create Pull Request*

I *think* that will work.

Thank you for your patience!

**Pull request merged**
