### PR TITLE
Updated Hungarian translation

### PR DESCRIPTION
**Pull request by Panyi**
Updated Hungarian translation
Status: 58%

### CODE REVIEW

**Comment by Panyi** [comment]
@iffy 
Is there any way to test my translation in the beta version of the application? I checked the file system and the language files in a "pak" file. Can i convert my tsx file to pak somehow?
Thanks.

**Comment by iffy** [comment]
@Panyi Unfortunately, there isn't a way to test translations right now. The `pak` files are for system translations, but the Buckets translation files are actually embedded in the `app.asar` file.

I can see how that would be very useful (and have wanted to add this in the past). I've filed this to track it: https://github.com/buckets/application/issues/631

**Comment by Panyi** [comment]
@iffy Thank you for the answer.
So then I'll wait for the next beta release to double check my work.

**Comment by Panyi** [comment]
I added also the missing strings from the Turkish file in order to fix the Github PR checks and tests

**Comment by iffy** [comment]
Köszönöm!

**Pull request merged**
